version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - restore_cache:
          key: -v3-{{ checksum "package.json" }}
      - run:
          name: Npm stuff
          command: |
            ls /usr/local/lib
            npm list -g
            npm install
            npm test
            ls
      - save_cache:
          key: -v3-{{ checksum "package.json" }}
          paths: /usr/local/lib/node_modules
