version: 2
jobs:
  build:
    working_directory: ~/tmp
    docker:
      - image: circleci/node:7
    steps:
      - checkout
      - restore_cache:
          key: -v3-{{ checksum "package.json" }}
      - save_cache:
          key: -v3-{{ checksum "package.json" }}
